module.exports.ROLES = {
  ADMIN: "ADMIN",
  OPERATIONADMIN: "OPERATIONADMIN",
  FINANCEADMIN: "FINANCEADMIN",
  COUNTRYMANAGER: "COUNTRYMANAGER",
  BRANCHMANAGER: "BRANCHMANAGER",
  USER: "USER",
  OPERATIONSTAFF: "OPERATIONSTAFF",
  FINANCESTAFF: "FINANCESTAFF",
  WORKSHOPSTAFF: "WORKSHOPSTAFF",
  WORKSHOPMANAGER: "WORKSHOPMANAGER"
};