const mongoose = require('mongoose');
require('dotenv').config();

const MONGO_URI = process.env.MONGO_URI;

const ROLES = {
  ADMIN: "ADMIN",
  OPERATIONADMIN: "OPERATIONADMIN",
  FINANCEADMIN: "FINANCEADMIN",
  COUNTRYMANAGER: "COUNTRYMANAGER",
  BRANCHMANAGER: "BRANCHMANAGER",
  OPERATIONSTAFF: "OPERATIONSTAFF",
  FINANCESTAFF: "FINANCESTAFF",
  WORKSHOPMANAGER: "WORKSHOPMANAGER",
  WORKSHOPSTAFF: "WORKSHOPSTAFF",
};

const PERMISSIONS = [
  "VEHICLE_VIEW", "VEHICLE_CREATE", "VEHICLE_EDIT", "VEHICLE_DELETE", "VEHICLE_TRANSFER", "VEHICLE_STATUS_CHANGE", "VEHICLE_APPROVE",
  "DRIVER_VIEW", "DRIVER_CREATE", "DRIVER_EDIT", "DRIVER_DELETE", "DRIVER_ONBOARD", "DRIVER_ASSIGN_VEHICLE",
  "BRANCH_VIEW", "BRANCH_CREATE", "BRANCH_EDIT", "BRANCH_DELETE",
  "STAFF_VIEW", "STAFF_CREATE", "STAFF_EDIT", "STAFF_DELETE", "STAFF_MANAGE_PERMISSIONS",
  "USER_VIEW", "USER_CREATE", "USER_EDIT", "USER_DELETE",
  "PURCHASE_ORDER_VIEW", "PURCHASE_ORDER_CREATE", "PURCHASE_ORDER_EDIT", "PURCHASE_ORDER_DELETE", "PURCHASE_ORDER_APPROVE",
  "SUPPLIER_VIEW", "SUPPLIER_CREATE", "SUPPLIER_EDIT", "SUPPLIER_DELETE",
  "PAYMENT_VIEW", "PAYMENT_CREATE", "PAYMENT_EDIT", "PAYMENT_DELETE", "PAYMENT_APPROVE",
  "LEDGER_VIEW", "LEDGER_CREATE", "LEDGER_EDIT", "LEDGER_DELETE",
  "INSURANCE_VIEW", "INSURANCE_CREATE", "INSURANCE_EDIT", "INSURANCE_DELETE",
  "INSURANCE_CLAIM_VIEW", "INSURANCE_CLAIM_CREATE", "INSURANCE_CLAIM_EDIT", "INSURANCE_CLAIM_DELETE",
  "WORK_ORDER_VIEW", "WORK_ORDER_CREATE", "WORK_ORDER_EDIT", "WORK_ORDER_DELETE", "WORK_ORDER_APPROVE",
  "SERVICE_BILL_VIEW", "SERVICE_BILL_CREATE", "SERVICE_BILL_EDIT", "SERVICE_BILL_DELETE",
  "INVENTORY_VIEW", "INVENTORY_CREATE", "INVENTORY_EDIT", "INVENTORY_DELETE",
  "TAX_VIEW", "TAX_CREATE", "TAX_EDIT", "TAX_DELETE",
  "ACCOUNTING_CODE_VIEW", "ACCOUNTING_CODE_CREATE", "ACCOUNTING_CODE_EDIT", "ACCOUNTING_CODE_DELETE",
  "AGREEMENT_VIEW", "AGREEMENT_CREATE", "AGREEMENT_EDIT", "AGREEMENT_DELETE",
  "LEASE_VIEW", "LEASE_CREATE", "LEASE_EDIT", "LEASE_DELETE",
  "SYSTEM_SETTINGS_VIEW", "SYSTEM_SETTINGS_EDIT",
  "STAFF_PERFORMANCE_VIEW", "STAFF_PERFORMANCE_EDIT",
  "AI_SERVICE_ACCESS", "REPORTS_VIEW", "DASHBOARD_VIEW",
  "ACCESS_CONTROL_MANAGE", "ROLE_TEMPLATE_VIEW", "ROLE_TEMPLATE_EDIT"
];

const roleTemplates = [
  {
    roleName: ROLES.ADMIN,
    permissions: PERMISSIONS,
    description: "Super Admin with full access"
  },
  {
    roleName: ROLES.COUNTRYMANAGER,
    permissions: [
        "VEHICLE_VIEW", "VEHICLE_CREATE", "VEHICLE_EDIT", "VEHICLE_TRANSFER", "VEHICLE_STATUS_CHANGE", "VEHICLE_APPROVE",
        "DRIVER_VIEW", "DRIVER_CREATE", "DRIVER_EDIT", "DRIVER_DELETE", "DRIVER_ONBOARD", "DRIVER_ASSIGN_VEHICLE",
        "BRANCH_VIEW", "STAFF_VIEW", "USER_VIEW", "PURCHASE_ORDER_VIEW", "PURCHASE_ORDER_APPROVE",
        "PAYMENT_VIEW", "PAYMENT_APPROVE", "LEDGER_VIEW", "INSURANCE_VIEW", "INSURANCE_CLAIM_VIEW",
        "WORK_ORDER_VIEW", "REPORTS_VIEW", "DASHBOARD_VIEW", "TAX_VIEW", "ACCOUNTING_CODE_VIEW",
        "AGREEMENT_VIEW", "STAFF_PERFORMANCE_VIEW", "SUPPLIER_VIEW", "SERVICE_BILL_VIEW"
    ],
    description: "Country-level manager with broad oversight"
  },
  {
    roleName: ROLES.BRANCHMANAGER,
    permissions: [
        "VEHICLE_VIEW", "VEHICLE_EDIT", "VEHICLE_STATUS_CHANGE", "VEHICLE_APPROVE",
        "DRIVER_VIEW", "DRIVER_EDIT", "DRIVER_ONBOARD", "DRIVER_ASSIGN_VEHICLE",
        "BRANCH_VIEW", "STAFF_VIEW", "USER_VIEW", "PURCHASE_ORDER_VIEW",
        "PAYMENT_VIEW", "LEDGER_VIEW", "WORK_ORDER_VIEW", "WORK_ORDER_APPROVE",
        "REPORTS_VIEW", "DASHBOARD_VIEW"
    ],
    description: "Branch-level manager focusing on daily operations"
  },
  {
    roleName: ROLES.FINANCESTAFF,
    permissions: [
        "VEHICLE_VIEW", "DRIVER_VIEW", "USER_VIEW", "PURCHASE_ORDER_VIEW", "PURCHASE_ORDER_CREATE",
        "PAYMENT_VIEW", "PAYMENT_CREATE", "LEDGER_VIEW", "LEDGER_CREATE",
        "INSURANCE_VIEW", "INSURANCE_CLAIM_VIEW", "TAX_VIEW"
    ],
    description: "Finance and accounting staff"
  },
  {
    roleName: ROLES.OPERATIONSTAFF,
    permissions: [
        "VEHICLE_VIEW", "VEHICLE_CREATE", "VEHICLE_EDIT",
        "DRIVER_VIEW", "DRIVER_CREATE", "DRIVER_EDIT", "DRIVER_ONBOARD",
        "BRANCH_VIEW", "WORK_ORDER_VIEW", "WORK_ORDER_CREATE"
    ],
    description: "Ground operations and driver management"
  }
];

const run = async () => {
    try {
        await mongoose.connect(MONGO_URI);
        console.log("Connected to DB");

        const RoleTemplate = require('../Src/modules/AccessControl/Model/RoleTemplate');
        
        for (const template of roleTemplates) {
            await RoleTemplate.findOneAndUpdate(
                { roleName: template.roleName },
                template,
                { upsert: true, new: true }
            );
            console.log(`Upserted RoleTemplate for ${template.roleName}`);
        }

        process.exit(0);
    } catch (error) {
        console.error("Error:", error);
        process.exit(1);
    }
};

run();
